class AlreadyProcessedException(Exception):
    pass


class UnknownError(Exception):
    pass
